### ISSUE TITLE
Final checklist

### ISSUE THREAD

**Issue by LinguList** [sigtyp/ST2022#8]
- [x] update datasets
- [x] new code for partial cognates when available from data (apply to mannburmish as well, needs new version)
- [x] link the documentation to the main README.md
- [x] add dates and link for registration or alternatively link to the website
